version: '3'

services:
  common-yapi-web:
    image: jayfong/yapi:latest
    environment:
      - YAPI_ADMIN_ACCOUNT=adminuser@acrool.com
      - YAPI_ADMIN_PASSWORD=acrool
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=common-yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - common-yapi-mongo
    links:
      - common-yapi-mongo
    restart: unless-stopped
  common-yapi-mongo:
    image: mongo:5.0.20
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped

networks:
  default:
    external:
      name: common_network
